name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rsteye.deb
            asset_name: rsteye-linux

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install pillow pyinstaller python-dotenv

    - name: Build binary with PyInstaller
      run: |
        source .venv/bin/activate
        pyinstaller --name RstEyeApp --onefile --add-data "med.gif:." --hidden-import=PIL.ImageTk --additional-hooks-dir=hooks app.py

    - name: Create Debian package
      run: |
        mkdir -p rsteye/DEBIAN
        mkdir -p rsteye/usr/bin
        cp dist/RstEyeApp rsteye/usr/bin/rsteye
        echo "Package: rsteye" > rsteye/DEBIAN/control
        echo "Version: 1.0" >> rsteye/DEBIAN/control
        echo "Section: base" >> rsteye/DEBIAN/control
        echo "Priority: optional" >> rsteye/DEBIAN/control
        echo "Architecture: amd64" >> rsteye/DEBIAN/control
        echo "Maintainer: Prince Roshan <princekrroshan01@gmail.com> >> rsteye/DEBIAN/control
        echo An App to remind users to take breaks and relax their eyes while working on the computer. >> rsteye/DEBIAN/control
        dpkg-deb --build rsteye
        mv rsteye.deb ${{ matrix.artifact_name }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
