name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rsteye.deb
            asset_name: rsteye.deb

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t rsteye-build .

    - name: Create container and copy binary
      run: |
        docker run --rm -v $(pwd):/host rsteye-build sh -c 'cp /app/dist/RstEyeApp /host/RstEyeApp'

    - name: Create Debian package structure and build package
      run: |
        mkdir -p rsteye/DEBIAN
        mkdir -p rsteye/usr/bin
        mkdir -p rsteye/lib/systemd/system
        cp RstEyeApp rsteye/usr/bin/RstEyeApp
        cp debian_pkg_files/rsteye.service rsteye/lib/systemd/system/rsteye.service
        cp debian_pkg_files/control rsteye/DEBIAN/control
        cp debian_pkg_files/postinst rsteye/DEBIAN/postinst
        cp debian_pkg_files/postrm rsteye/DEBIAN/postrm
        chmod 755 rsteye/DEBIAN/postinst
        chmod 755 rsteye/DEBIAN/postrm
        dpkg-deb --build rsteye

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.9.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: rsteye.deb
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
